FEATURES = {
    'dev': [
        'spud_tagging',
        'manage_team_admins',
        'clubs',
        'nays_survey',
        'affiliate_login',  # just login & dashboard page    
        'invite_clubs',
        'challenges_landing_page',
        'challenges_only_override',
        'club_register',
        # 'challenge_challenge',
        'challenge_tree',
        'email_error_logs',
        'tracking_pixels',
        'challenge_management',
        'challenge_dreamsforkids_piechallenge',
        'challenge_bpt_memorial_field_fund_rak',
        'challenge_dreamsforkids_payitforward',
    ],
    'stage': [
        # 'spud_tagging',
        # 'manage_team_admins',
        # 'clubs',
        'nays_survey',
        # 'affiliate_login',
        # 'invite_clubs',
        'challenges_landing_page',
        'challenges_only_override',
        # 'challenge_challenge',
        'club_register',
        'challenge_tree',
        'email_error_logs',
        'tracking_pixels',
        # 'stripe_ein_validation',
        'all_fans_auto_follow_main_spudder_fan',
        'challenge_dreamsforkids_piechallenge',
        'challenge_bpt_memorial_field_fund_rak',
        'challenge_dreamsforkids_payitforward',
    ],
    'live': [
        'club_register',
        'google_analytics',
        'alexa_analytics',
        'nays_survey',
        'challenges_landing_page',
        'challenges_only_override',
        'email_error_logs',
        'tracking_pixels',
        'all_fans_auto_follow_main_spudder_fan',
        'challenge_dreamsforkids_piechallenge',
        'challenge_dreamsforkids_payitforward',
        'challenge_bpt_memorial_field_fund_rak',
    ]
}


